<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { usePhraseCatalog } from '@/i18n/phrase'
import { Archive, ArchiveRestore, Bot, CheckCircle2, ChevronLeft, CircleStop, LoaderCircle, Menu, MessageSquarePlus, Pencil, Pin, Search, Send, Settings2, Sparkles, Trash2, Wifi, WifiOff, X } from '@lucide/vue'
import AiMarkdown from '@/components/ai/AiMarkdown.vue'
import AiSettings from '@/components/ai/AiSettings.vue'
import { aiApi,runEventURL } from '@/lib/aiApi'
import type { AIMessage,AIModel,AIProvider,AIRun,AIRunSnapshot,AISession,AIToolCall } from '@/types/ai'

usePhraseCatalog(() => import('@/i18n/pages/AiView/en-US').then((module) => module.default))

const route=useRoute();const router=useRouter()
const providers=ref<AIProvider[]>([]);const models=ref<AIModel[]>([]);const sessions=ref<AISession[]>([]);const messages=ref<AIMessage[]>([]);const toolCalls=ref<AIToolCall[]>([])
const currentRun=ref<AIRun>();const streamText=ref('');const search=ref('');const input=ref('');const error=ref('');const loading=ref(true);const sending=ref(false);const connected=ref(false);const settingsOpen=ref(false);const sessionDrawer=ref(false)
const newSessionOpen=ref(false);const creatingSession=ref(false);const showArchived=ref(false);const draftModelId=ref('');const draftTitle=ref('')
const lastCompletedRunId=ref('');const proposing=ref(false)
const messageCursor=ref('');const loadingOlder=ref(false)
const messageEnd=ref<HTMLElement>();const composer=ref<HTMLTextAreaElement>();let source:EventSource|undefined;let searchTimer:number|undefined
const activeId=computed(()=>String(route.params.sessionId||''));const active=computed(()=>sessions.value.find(item=>item.id===activeId.value));
const availableModels=computed(()=>models.value.filter(model=>model.enabled&&providers.value.some(provider=>provider.id===model.providerId&&provider.enabled)))
const modelGroups=computed(()=>providers.value.filter(provider=>provider.enabled).map(provider=>({provider,models:availableModels.value.filter(model=>model.providerId===provider.id)})).filter(group=>group.models.length))
const draftModel=computed(()=>availableModels.value.find(item=>item.id===draftModelId.value))
const activeModel=computed(()=>models.value.find(item=>item.id===active.value?.modelId))
const activeProvider=computed(()=>providers.value.find(item=>item.id===active.value?.providerId))
const runActive=computed(()=>!!currentRun.value&&!['completed','failed','cancelled','interrupted'].includes(currentRun.value.status))
const modelQueued=computed(()=>runActive.value&&!!active.value&&!!currentRun.value&&active.value.modelId!==currentRun.value.modelId)
const runState=computed(()=>{if(!runActive.value)return{label:'就绪',tone:'idle'};if(currentRun.value?.status==='pending_approval')return{label:'等待确认',tone:'approval'};if(!connected.value)return{label:'正在重连',tone:'offline'};return{label:'正在生成',tone:'online'}})
const contextUsage=computed(()=>{const model=models.value.find(item=>item.id===active.value?.modelId);if(!model)return 0;const chars=messages.value.reduce((sum,item)=>sum+item.content.length,0)+streamText.value.length;return Math.min(100,Math.round(chars/4/model.contextWindow*100))})
const grouped=computed(()=>{const result:{label:string;items:AISession[]}[]=[];const now=new Date();for(const item of sessions.value.filter(item=>item.title.toLowerCase().includes(search.value.toLowerCase()))){const date=new Date(item.lastMessageAt);const days=Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime()-new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime())/86400000);const label=showArchived.value?'已归档':item.pinned?'置顶':days===0?'今天':days===1?'昨天':'更早';let group=result.find(group=>group.label===label);if(!group){group={label,items:[]};result.push(group)}group.items.push(item)}return result})
const pendingApproval=computed(()=>toolCalls.value.find(item=>item.status==='pending_approval'))

function friendlyTool(name:string){return name.replace(/^host_/,'').replaceAll('_',' · ')}
function hasActivityLink(name:string){return ['host_app_action','host_diagnostic_start','host_docker_task','host_site_change','host_job_input'].includes(name)}
function scrollBottom(){void nextTick(()=>messageEnd.value?.scrollIntoView({behavior:'smooth'}))}
async function loadAll(){error.value='';try{[providers.value,models.value,sessions.value]=await Promise.all([aiApi.providers.list(),aiApi.models(),aiApi.sessions.list(search.value,showArchived.value)]);if(activeId.value&&!sessions.value.some(item=>item.id===activeId.value)){await router.replace('/ai')}else if(activeId.value){await loadMessages()}else if(sessions.value[0])await router.replace(`/ai/s/${sessions.value[0].id}`)}catch(reason){error.value=reason instanceof Error?reason.message:'AI 工作台加载失败'}finally{loading.value=false}}
async function loadMessages(){closeStream();messages.value=[];messageCursor.value='';toolCalls.value=[];currentRun.value=undefined;lastCompletedRunId.value='';streamText.value='';if(!activeId.value)return;try{const page=await aiApi.sessions.messages(activeId.value);messages.value=page.items;messageCursor.value=page.nextCursor||'';lastCompletedRunId.value=[...messages.value].reverse().find(item=>item.role==='assistant'&&item.runId)?.runId||'';const session=active.value;if(session?.running&&session.activeRunId)openStream(session.activeRunId);else if(session?.lastRunId&&['interrupted','failed'].includes(session.lastRunStatus||''))currentRun.value=await aiApi.runs.get(session.lastRunId)}catch(reason){error.value=reason instanceof Error?reason.message:'对话读取失败'}scrollBottom()}
async function loadOlder(){if(!activeId.value||!messageCursor.value||loadingOlder.value)return;loadingOlder.value=true;try{const page=await aiApi.sessions.messages(activeId.value,messageCursor.value);messages.value=[...page.items,...messages.value];messageCursor.value=page.nextCursor||''}catch(reason){error.value=reason instanceof Error?reason.message:'更早消息加载失败'}finally{loadingOlder.value=false}}
function openNewSession(){const first=availableModels.value[0];if(!first){settingsOpen.value=true;return};draftModelId.value=availableModels.value.some(item=>item.id===active.value?.modelId)?active.value!.modelId:(availableModels.value.find(item=>item.isDefault)?.id||first.id);draftTitle.value='';newSessionOpen.value=true}
async function createSession(){const model=draftModel.value;const provider=providers.value.find(item=>item.id===model?.providerId);if(!provider||!model||creatingSession.value)return;creatingSession.value=true;error.value='';try{const item=await aiApi.sessions.create(provider.id,model.id,draftTitle.value.trim());showArchived.value=false;sessions.value.unshift(item);newSessionOpen.value=false;await router.push(`/ai/s/${item.id}`);sessionDrawer.value=false}catch(reason){error.value=reason instanceof Error?reason.message:'新建会话失败'}finally{creatingSession.value=false}}
async function send(){const content=input.value.trim();if(!content||!active.value||sending.value)return;sending.value=true;error.value='';input.value='';void nextTick(()=>{if(composer.value)composer.value.style.height='auto'});messages.value.push({id:`local-${Date.now()}`,sessionId:active.value.id,role:'user',content,createdAt:new Date().toISOString()});scrollBottom();try{const result=await aiApi.sessions.send(active.value.id,content);openStream(result.runId)}catch(reason){input.value=content;error.value=reason instanceof Error?reason.message:'发送失败';await loadMessages()}finally{sending.value=false}}
function onKeydown(event:KeyboardEvent){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}
function resizeComposer(event:Event){const target=event.target as HTMLTextAreaElement;target.style.height='auto';target.style.height=`${Math.min(target.scrollHeight,160)}px`}
function openStream(runId:string){closeStream();connected.value=false;source=new EventSource(runEventURL(runId),{withCredentials:true});source.onopen=()=>connected.value=true;source.onerror=()=>{connected.value=false};const listen=(name:string,handler:(value:any)=>void)=>source?.addEventListener(name,event=>{try{handler(JSON.parse((event as MessageEvent).data))}catch{}});listen('run.snapshot',(value:AIRunSnapshot)=>{currentRun.value=value.run;toolCalls.value=value.toolCalls;messages.value=value.messages});listen('message.delta',(value:{delta:string})=>{streamText.value+=value.delta;scrollBottom()});listen('message.completed',(value:AIMessage)=>{streamText.value='';if(!messages.value.some(item=>item.id===value.id))messages.value.push(value)});listen('approval.required',(value:AIToolCall)=>{toolCalls.value=[...toolCalls.value.filter(item=>item.id!==value.id),value];if(currentRun.value)currentRun.value.status='pending_approval'});listen('tool.started',mergeTool);listen('tool.completed',mergeTool);for(const terminal of ['run.completed','run.failed','run.cancelled'] as const)listen(terminal,(value:AIRun)=>{currentRun.value=value;if(terminal==='run.completed')lastCompletedRunId.value=value.id;closeStream();void loadMessages();void refreshSessions()});listen('auth.expired',()=>{closeStream();error.value='登录已过期，请重新登录。'})}
function mergeTool(value:AIToolCall){toolCalls.value=[...toolCalls.value.filter(item=>item.id!==value.id),value]}
function closeStream(){source?.close();source=undefined;connected.value=false}
async function decide(approve:boolean){const call=pendingApproval.value;if(!call||!currentRun.value)return;try{await aiApi.runs.decision(currentRun.value.id,call.id,approve);call.status=approve?'running':'rejected';openStream(currentRun.value.id)}catch(reason){error.value=reason instanceof Error?reason.message:'审批提交失败'}}
async function cancelRun(){if(!currentRun.value)return;await aiApi.runs.cancel(currentRun.value.id);closeStream();await loadMessages();await refreshSessions()}
async function retryRun(){if(!currentRun.value)return;try{const result=await aiApi.runs.retry(currentRun.value.id);openStream(result.runId);await refreshSessions()}catch(reason){error.value=reason instanceof Error?reason.message:'重试失败'}}
async function refreshSessions(){sessions.value=await aiApi.sessions.list(search.value,showArchived.value)}
async function toggleArchiveView(){showArchived.value=!showArchived.value;search.value='';if(activeId.value)await router.push('/ai');await refreshSessions();if(sessions.value[0])await router.push(`/ai/s/${sessions.value[0].id}`)}
async function proposeFlow(){if(!lastCompletedRunId.value||proposing.value)return;proposing.value=true;error.value='';try{await aiApi.runs.propose(lastCompletedRunId.value);settingsOpen.value=true}catch(reason){error.value=reason instanceof Error?reason.message:'流程提案生成失败'}finally{proposing.value=false}}
async function updateModel(event:Event){const modelId=(event.target as HTMLSelectElement).value;const model=models.value.find(item=>item.id===modelId);const provider=providers.value.find(item=>item.id===model?.providerId);if(!active.value||!model||!provider)return;error.value='';try{const updated=await aiApi.sessions.update(active.value.id,{providerId:provider.id,modelId:model.id});sessions.value=sessions.value.map(item=>item.id===updated.id?updated:item)}catch(reason){error.value=reason instanceof Error?reason.message:'模型切换失败'}}
async function rename(item?:AISession){const target=item||active.value;if(!target)return;const title=prompt('会话名称',target.title)?.trim();if(!title)return;try{const updated=await aiApi.sessions.update(target.id,{title});sessions.value=sessions.value.map(value=>value.id===updated.id?updated:value)}catch(reason){error.value=reason instanceof Error?reason.message:'会话重命名失败'}}
async function togglePin(item:AISession){try{const updated=await aiApi.sessions.update(item.id,{pinned:!item.pinned});sessions.value=sessions.value.map(value=>value.id===updated.id?updated:value)}catch(reason){error.value=reason instanceof Error?reason.message:'会话置顶失败'}}
async function refreshAfterSessionLeaves(item:AISession){const wasActive=item.id===activeId.value;if(wasActive)await router.push('/ai');await refreshSessions();if(wasActive&&sessions.value[0])await router.push(`/ai/s/${sessions.value[0].id}`)}
async function archive(item:AISession){try{await aiApi.sessions.update(item.id,{archived:true});await refreshAfterSessionLeaves(item)}catch(reason){error.value=reason instanceof Error?reason.message:'会话归档失败'}}
async function restore(item:AISession){try{await aiApi.sessions.update(item.id,{archived:false});await refreshAfterSessionLeaves(item)}catch(reason){error.value=reason instanceof Error?reason.message:'会话恢复失败'}}
async function remove(item:AISession){if(!confirm(`删除会话“${item.title}”？此操作不可恢复。`))return;try{await aiApi.sessions.remove(item.id);await refreshAfterSessionLeaves(item)}catch(reason){error.value=reason instanceof Error?reason.message:'会话删除失败'}}
watch(activeId,loadMessages);watch(search,()=>{if(searchTimer)window.clearTimeout(searchTimer);searchTimer=window.setTimeout(refreshSessions,250)})
onMounted(loadAll);onBeforeUnmount(()=>{closeStream();if(searchTimer)window.clearTimeout(searchTimer)})
</script>

<template>
  <div class="ai-workspace" :class="{'ai-workspace--drawer':sessionDrawer}">
    <button v-if="sessionDrawer" class="ai-session-overlay" aria-label="关闭会话列表" @click="sessionDrawer=false" />
    <aside class="ai-session-panel">
      <header><div><span class="ai-brand-mark"><Sparkles :size="16"/></span><span><strong>AI 助手</strong><small>{{showArchived?'已归档会话':`${sessions.length} 个会话`}}</small></span></div><button class="icon-button ai-session-close" aria-label="关闭会话列表" @click="sessionDrawer=false"><X :size="18"/></button></header>
      <button class="ai-new-chat" @click="openNewSession"><MessageSquarePlus :size="17"/>新建会话</button>
      <div class="ai-session-filter"><label class="ai-search"><Search :size="15"/><input v-model="search" placeholder="搜索会话"/></label><button class="ai-archive-filter" :class="{active:showArchived}" :title="showArchived?'返回当前会话':'查看已归档会话'" :aria-label="showArchived?'返回当前会话':'查看已归档会话'" @click="toggleArchiveView"><ArchiveRestore v-if="showArchived" :size="16"/><Archive v-else :size="16"/></button></div>
      <div class="ai-session-groups">
        <section v-for="group in grouped" :key="group.label"><h3>{{group.label}}</h3>
          <div v-for="item in group.items" :key="item.id" class="ai-session-item" :class="{active:item.id===activeId}">
            <RouterLink :to="`/ai/s/${item.id}`" @click="sessionDrawer=false"><strong>{{item.title}}</strong><small>{{item.modelName}} · {{new Date(item.lastMessageAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></RouterLink>
            <span v-if="item.running" class="ai-running-dot" title="运行中"/>
            <div class="ai-session-actions"><button title="重命名" aria-label="重命名会话" @click="rename(item)"><Pencil :size="13"/></button><button v-if="!showArchived" :title="item.pinned?'取消置顶':'置顶'" :aria-label="item.pinned?'取消置顶':'置顶会话'" @click="togglePin(item)"><Pin :size="13"/></button><button v-if="showArchived" title="恢复会话" aria-label="恢复会话" @click="restore(item)"><ArchiveRestore :size="13"/></button><button v-else title="归档" aria-label="归档会话" @click="archive(item)"><Archive :size="13"/></button><button title="删除" aria-label="删除会话" @click="remove(item)"><Trash2 :size="13"/></button></div>
          </div>
        </section>
        <div v-if="!grouped.length" class="ai-session-empty"><Search v-if="search" :size="20"/><Archive v-else-if="showArchived" :size="20"/><MessageSquarePlus v-else :size="20"/><strong>{{search?'没有匹配会话':showArchived?'暂无归档会话':'还没有会话'}}</strong><small>{{search?'换个关键词试试':showArchived?'归档的会话会保留在这里':'新建会话后可独立选择模型'}}</small></div>
      </div>
    </aside>

    <section class="ai-chat-panel">
      <div v-if="!availableModels.length&&!loading" class="ai-onboarding"><div class="ai-orb"><Bot :size="32"/></div><span class="eyebrow">KPanel native agent</span><h1>{{providers.length?'还差一个可用模型':'连接你的第一个模型'}}</h1><p>{{providers.length?'测试 API 并同步模型，或手工补充一个兼容模型。':'选择常用服务商，只需填写密钥；连接测试和模型同步会自动完成。'}} 密钥加密保存在本机，模型只能调用 KPanel 注册工具。</p><div class="ai-onboarding-steps"><span class="done"><CheckCircle2 :size="15"/>选择 API</span><i/><span>验证连接</span><i/><span>选择模型</span></div><button class="button button--primary" @click="settingsOpen=true"><Settings2 :size="17"/>{{providers.length?'继续配置模型':'添加 API'}}</button></div>
      <template v-else-if="active">
        <header class="ai-chat-header">
          <button class="icon-button ai-session-toggle" aria-label="打开会话列表" @click="sessionDrawer=true"><Menu :size="19"/></button>
          <button class="ai-chat-title" title="重命名会话" @click="rename()"><strong>{{active.title}}</strong><small>{{activeProvider?.name||active.providerName}} · {{activeModel?.displayName||active.modelName}}</small></button>
          <div class="ai-chat-controls"><label class="ai-model-picker"><span>模型</span><select :value="active.modelId" :title="runActive?'切换后从下一轮开始使用':'切换当前会话模型'" aria-label="选择模型" @change="updateModel"><option v-if="!active.modelAvailable" :value="active.modelId" disabled>{{active.modelName}}（不可用）</option><optgroup v-for="group in modelGroups" :key="group.provider.id" :label="group.provider.name"><option v-for="model in group.models" :key="model.id" :value="model.id">{{model.displayName}}</option></optgroup></select></label><span v-if="modelQueued" class="ai-next-model">下一轮</span><span class="ai-context" :title="`上下文使用约 ${contextUsage}%`"><i :style="{width:`${contextUsage}%`}"/>{{contextUsage}}%</span><span class="ai-connection" :class="runState.tone"><Wifi v-if="runState.tone==='online'" :size="14"/><WifiOff v-else-if="runState.tone==='offline'" :size="14"/><CheckCircle2 v-else :size="14"/>{{runState.label}}</span><button v-if="runActive" class="icon-button" title="取消运行" aria-label="取消运行" @click="cancelRun"><CircleStop :size="18"/></button><button v-if="lastCompletedRunId" class="button button--small ai-propose-button" :disabled="proposing" title="生成待审核流程提案" @click="proposeFlow">沉淀流程</button><button class="icon-button" title="添加 API 或管理模型" aria-label="AI 设置" @click="settingsOpen=true"><Settings2 :size="18"/></button></div>
        </header>
        <div v-if="!active.modelAvailable" class="ai-model-warning"><span>当前模型已停用或 Provider 不可用，请切换模型后继续。</span><button class="button button--small" @click="settingsOpen=true">管理模型</button></div>
        <div class="ai-messages">
          <button v-if="messageCursor" class="button button--small ai-load-older" :disabled="loadingOlder" @click="loadOlder">{{loadingOlder?'加载中…':'加载更早消息'}}</button>
          <div v-if="!messages.length&&!streamText" class="ai-welcome"><div class="ai-orb ai-orb--small"><Sparkles :size="23"/></div><h2>今天想管理什么？</h2><p>我会先读取真实状态；任何写入、删除或 exec 都会等待你逐次确认。</p><div><button @click="input='检查服务器资源与异常状态'">检查服务器状态</button><button @click="input='列出当前运行中的容器并总结健康情况'">查看容器健康</button><button @click="input='检查网站与应用状态，不要执行修改'">巡检网站和应用</button></div></div>
          <article v-for="message in messages" :key="message.id" :class="['ai-message',`ai-message--${message.role}`]"><div class="ai-message__avatar"><Bot v-if="message.role==='assistant'" :size="17"/><span v-else>你</span></div><div class="ai-message__body"><AiMarkdown :content="message.content"/><small v-if="message.role==='assistant'">{{message.modelName||active.modelName}}</small></div></article>
          <article v-if="streamText" class="ai-message ai-message--assistant"><div class="ai-message__avatar"><Bot :size="17"/></div><div class="ai-message__body"><AiMarkdown :content="streamText"/><span class="ai-cursor"/></div></article>
          <article v-else-if="runActive&&!pendingApproval" class="ai-message ai-message--assistant ai-message--thinking"><div class="ai-message__avatar"><Bot :size="17"/></div><div class="ai-message__body"><div class="ai-thinking-dots"><i/><i/><i/></div><small>{{connected?'正在理解并规划任务…':'连接中，正在恢复本轮输出…'}}</small></div></article>
          <div v-for="call in toolCalls" :key="call.id" class="ai-tool-card" :class="`ai-tool-card--${call.status}`"><header><span class="ai-tool-icon"><Settings2 :size="15"/></span><div><strong>{{friendlyTool(call.name)}}</strong><small>{{call.status==='pending_approval'?'等待你的批准':call.status==='running'?'正在执行':call.status==='completed'?'已完成':call.status}}</small></div></header><details><summary>查看结构化参数与结果</summary><pre>{{call.argumentsPreview||call.arguments}}</pre><pre v-if="call.resultPreview">{{call.resultPreview}}</pre></details><footer v-if="call.status==='pending_approval'"><p>此操作会修改宿主机真实状态。批准前请核对目标与参数。</p><div><button class="button" @click="decide(false)">拒绝</button><button class="button button--primary" @click="decide(true)">批准本次操作</button></div></footer><footer v-else-if="call.status==='completed'&&hasActivityLink(call.name)"><p>后台任务已提交，可在活动记录中继续查看进度。</p><RouterLink class="button" to="/activity">打开活动记录</RouterLink></footer></div>
          <div v-if="currentRun&&['failed','interrupted'].includes(currentRun.status)" class="ai-run-error"><strong>{{currentRun.status==='interrupted'?'运行因 Panel 重启中断':'运行失败'}}</strong><span>{{currentRun.errorMessage||currentRun.errorCode}}</span><button class="button button--small" @click="retryRun">重试本轮</button></div>
          <div ref="messageEnd"/>
        </div>
        <footer class="ai-composer-wrap"><p v-if="error" class="ai-inline-error">{{error}}</p><div class="ai-composer"><textarea ref="composer" v-model="input" rows="1" maxlength="16384" :placeholder="runActive?'可继续补充要求，将加入当前任务…':'告诉 AI 你想完成什么…'" @input="resizeComposer" @keydown="onKeydown"/><button :disabled="!input.trim()||sending" aria-label="发送" @click="send"><LoaderCircle v-if="sending" class="spin" :size="18"/><Send v-else :size="18"/></button></div><small><span>{{activeModel?.displayName||active.modelName}}</span><b>·</b><span>{{runActive?'切换模型从下一轮生效':'Enter 发送 · Shift+Enter 换行'}}</span><b>·</b><span>写操作始终确认</span></small></footer>
      </template>
      <div v-else-if="!loading" class="ai-empty-chat"><button class="ai-session-toggle button" @click="sessionDrawer=true"><ChevronLeft :size="16"/>打开会话列表</button><Sparkles :size="30"/><h2>{{showArchived?'选择一个归档会话':'开始一次新的对话'}}</h2><p>{{showArchived?'可以恢复、查看或删除归档会话。':'先选择 API 与模型；每个会话相互独立，之后也可随时切换。'}}</p><button v-if="!showArchived" class="button button--primary" @click="openNewSession">选择模型并新建</button></div>
    </section>
    <div v-if="newSessionOpen" class="ai-settings-backdrop ai-new-session-backdrop" @click.self="newSessionOpen=false">
      <section class="ai-new-session-dialog" role="dialog" aria-modal="true" aria-label="新建 AI 会话">
        <header><div class="ai-dialog-icon"><MessageSquarePlus :size="20"/></div><div><span class="eyebrow">New conversation</span><h2>新建会话</h2><p>为这次对话选择模型，后续可随时更换。</p></div><button class="icon-button" aria-label="关闭新建会话" @click="newSessionOpen=false"><X :size="18"/></button></header>
        <div class="ai-new-session-form"><label>会话名称 <span>可选</span><input v-model="draftTitle" maxlength="120" placeholder="例如：服务器日常巡检"/></label><label>API 与模型<select v-model="draftModelId" aria-label="新会话模型"><optgroup v-for="group in modelGroups" :key="group.provider.id" :label="group.provider.name"><option v-for="model in group.models" :key="model.id" :value="model.id">{{model.displayName}}</option></optgroup></select></label><div v-if="draftModel" class="ai-model-summary"><CheckCircle2 :size="17"/><span><strong>{{draftModel.displayName}}</strong><small>{{providers.find(item=>item.id===draftModel?.providerId)?.name}} · {{draftModel.contextWindow.toLocaleString()}} tokens · {{draftModel.toolCalling?'支持工具调用':'仅对话'}}</small></span></div></div>
        <footer><button class="button" @click="newSessionOpen=false">取消</button><button class="button button--primary" :disabled="!draftModelId||creatingSession" @click="createSession"><LoaderCircle v-if="creatingSession" class="spin" :size="16"/>创建会话</button></footer>
      </section>
    </div>
    <AiSettings v-if="settingsOpen" :providers="providers" :models="models" @close="settingsOpen=false" @refresh="loadAll"/>
  </div>
</template>
