import type { InjectionKey, Ref } from 'vue'

export const MAX_EMBEDDED_BROWSER_TABS = 8
export const MAX_LIVE_EMBEDDED_BROWSER_TABS = 2
export const EMBEDDED_BROWSER_SLEEP_MS = 45_000

export interface EmbeddedBrowserTarget {
  href: string
  hostname: string
  mixedContent: boolean
}

export interface EmbeddedBrowserShortcut {
  id: string
  kind: 'app' | 'site'
  name: string
  url: string
  iconURL?: string
}

/** URL-capable desktop entries shared with the lightweight browser start page. */
export const embeddedBrowserShortcutsKey = Symbol(
  'embedded-browser-shortcuts',
) as InjectionKey<Readonly<Ref<EmbeddedBrowserShortcut[]>>>

/**
 * Accept only ordinary web URLs generated by desktop shortcuts or entered by
 * an authenticated administrator. Credentials and non-web schemes are
 * rejected before anything reaches an iframe.
 */
export function resolveEmbeddedBrowserTarget(
  raw: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserTarget | undefined {
  const value = Array.isArray(raw) ? raw[0] : raw
  if (typeof value !== 'string' || !value || value.length > 2_048) return undefined
  try {
    const url = new URL(value)
    if ((url.protocol !== 'http:' && url.protocol !== 'https:') || url.username || url.password) {
      return undefined
    }
    return {
      href: url.href,
      hostname: url.hostname,
      mixedContent: panelProtocol === 'https:' && url.protocol === 'http:',
    }
  } catch {
    return undefined
  }
}

/** Accept a full URL or a bare hostname typed into the browser address field. */
export function resolveEmbeddedBrowserInput(
  raw: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserTarget | undefined {
  if (typeof raw !== 'string') return undefined
  const value = raw.trim()
  if (!value) return undefined
  const candidate = /^https?:\/\//i.test(value) ? value : `https://${value}`
  return resolveEmbeddedBrowserTarget(candidate, panelProtocol)
}
