import type { InjectionKey, Ref } from 'vue'

export const MAX_EMBEDDED_BROWSER_TABS = 8
export const MAX_LIVE_EMBEDDED_BROWSER_TABS = 2
export const EMBEDDED_BROWSER_SLEEP_MS = 45_000

export interface EmbeddedBrowserTarget {
  href: string
  hostname: string
  mixedContent: boolean
}

export interface EmbeddedBrowserShortcut {
  id: string
  kind: 'app' | 'site'
  name: string
  url: string
  iconURL?: string
}

export type EmbeddedBrowserSearchEngine = 'bing' | 'google'

export interface EmbeddedBrowserStartResolution {
  kind: 'url' | 'search'
  target: EmbeddedBrowserTarget
  query?: string
  searchEngine?: EmbeddedBrowserSearchEngine
}

/** URL-capable desktop entries shared with the lightweight browser start page. */
export const embeddedBrowserShortcutsKey = Symbol(
  'embedded-browser-shortcuts',
) as InjectionKey<Readonly<Ref<EmbeddedBrowserShortcut[]>>>

/** Server public-network country code reused from the desktop entry snapshot. */
export const embeddedBrowserCountryCodeKey = Symbol(
  'embedded-browser-country-code',
) as InjectionKey<Readonly<Ref<string>>>

/**
 * Accept only ordinary web URLs generated by desktop shortcuts or entered by
 * an authenticated administrator. Credentials and non-web schemes are
 * rejected before anything reaches an iframe.
 */
export function resolveEmbeddedBrowserTarget(
  raw: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserTarget | undefined {
  const value = Array.isArray(raw) ? raw[0] : raw
  if (typeof value !== 'string' || !value || value.length > 2_048) return undefined
  try {
    const url = new URL(value)
    if ((url.protocol !== 'http:' && url.protocol !== 'https:') || url.username || url.password) {
      return undefined
    }
    return {
      href: url.href,
      hostname: url.hostname,
      mixedContent: panelProtocol === 'https:' && url.protocol === 'http:',
    }
  } catch {
    return undefined
  }
}

/** Accept a full URL or a bare hostname typed into the browser address field. */
export function resolveEmbeddedBrowserInput(
  raw: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserTarget | undefined {
  if (typeof raw !== 'string') return undefined
  const value = raw.trim()
  if (!value) return undefined
  const candidate = /^https?:\/\//i.test(value) ? value : `https://${value}`
  return resolveEmbeddedBrowserTarget(candidate, panelProtocol)
}

export function preferredEmbeddedBrowserSearchEngine(
  countryCode: unknown,
): EmbeddedBrowserSearchEngine {
  if (typeof countryCode !== 'string' || !countryCode.trim()) return 'bing'
  return countryCode.trim().toUpperCase() === 'CN' ? 'bing' : 'google'
}

function looksLikeWebAddress(value: string): boolean {
  if (/^https?:\/\//i.test(value) || /\s/.test(value)) return /^https?:\/\//i.test(value)
  const authority = value.split(/[/?#]/, 1)[0] || ''
  if (/^\[[0-9a-f:]+\](?::\d+)?$/i.test(authority)) return true
  const hostname = authority.replace(/:\d+$/, '').toLowerCase()
  return hostname === 'localhost'
    || /^(?:\d{1,3}\.){3}\d{1,3}$/.test(hostname)
    || hostname.includes('.')
}

/**
 * Resolve the start-page omnibox as either a web address or a search query.
 * Unknown server location deliberately falls back to Bing, which remains
 * reachable in both domestic and international deployments.
 */
export function resolveEmbeddedBrowserStartInput(
  raw: unknown,
  countryCode: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserStartResolution | undefined {
  if (typeof raw !== 'string') return undefined
  const value = raw.trim()
  if (!value || value.length > 2_048) return undefined

  if (looksLikeWebAddress(value)) {
    const target = resolveEmbeddedBrowserInput(value, panelProtocol)
    return target ? { kind: 'url', target } : undefined
  }

  if (/^[a-z][a-z\d+.-]*:/i.test(value) || value.length > 512) return undefined
  const searchEngine = preferredEmbeddedBrowserSearchEngine(countryCode)
  const searchURL = new URL(
    searchEngine === 'bing' ? 'https://cn.bing.com/search' : 'https://www.google.com/search',
  )
  if (searchEngine === 'google') searchURL.searchParams.set('igu', '1')
  searchURL.searchParams.set('q', value)
  const target = resolveEmbeddedBrowserTarget(searchURL.href, panelProtocol)
  return target ? { kind: 'search', target, query: value, searchEngine } : undefined
}
