export interface EmbeddedBrowserTarget {
  href: string
  hostname: string
  mixedContent: boolean
}

/**
 * Accept only ordinary web URLs generated by configured KPanel sites.
 * Credentials and non-web schemes are rejected before anything reaches an iframe.
 */
export function resolveEmbeddedBrowserTarget(
  raw: unknown,
  panelProtocol = typeof window === 'undefined' ? 'http:' : window.location.protocol,
): EmbeddedBrowserTarget | undefined {
  const value = Array.isArray(raw) ? raw[0] : raw
  if (typeof value !== 'string' || !value || value.length > 2_048) return undefined
  try {
    const url = new URL(value)
    if ((url.protocol !== 'http:' && url.protocol !== 'https:') || url.username || url.password) {
      return undefined
    }
    return {
      href: url.href,
      hostname: url.hostname,
      mixedContent: panelProtocol === 'https:' && url.protocol === 'http:',
    }
  } catch {
    return undefined
  }
}
